### ISSUE TITLE
录制完成 无视频 - 显示错误

### ISSUE THREAD

**Issue by Taekkjin** [Bililive/BililiveRecorder#10]
[10:29:35] ERROR  System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at BililiveRecorder.Core.Utils.ReadB(NetworkStream stream, Byte[] buffer, Int32 offset, Int32 count)
   at BililiveRecorder.Core.DanmakuReceiver.ReceiveMessageLoop() Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

**Comment by Genteure** [comment]
无视频具体是什么表现？
没有视频文件？视频文件大小为0？
你贴的这条错误消息是弹幕服务器连接被断开，不会影响到直播的录制。

**Comment by Taekkjin** [comment]
更新至 1.0.11.0  之后录制完成后都没有flv视频文件

**Comment by Genteure** [comment]
没有完整日志不是很能确定具体是为什么，看起来玄学网络问题可能性比较大。
目前没有对不稳定的网络做一些优化，一切都是基于录制的机子有稳定的网络连接的前提上做的。

和新版本无关，新版本只改了生成的文件名。有人反馈主播名字带有特殊符号时不能录制。

**Comment by Taekkjin** [comment]
谢谢了

**Comment by Genteure** [comment]
如果一直出现类似的问题的话再说吧，我确实有打算优化一下这一块的想法。

**Comment by Genteure** [comment]
是更新的问题。。录制的路径给改坏了，又新发了个版本修复了这个问题。
1.0.11.0 录制的文件在 `%userprofile%\AppData\Local\Apps\2.0` 里面某一个文件夹，可以搜索一下 `*.flv`

**Comment by Taekkjin** [comment]
谢谢，找到flv视频了
