### ISSUE TITLE
Cli没有录制

### ISSUE THREAD

**Issue by U5ER-N4ME** [Bililive/BililiveRecorder#172]
运行环境：Ubuntu 20.04.1 LTS
使用nohup挂在后台，下附的输出内容也是nohup.out的节选。

部分输出内容（已隐藏直播间ID）

```
[21:03:22 WRN] [] Error running ProcessDataAsync
System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.IO.Pipelines.StreamPipeReader.ReadAsync(CancellationToken cancellationToken)
   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.ReadPipeAsync(PipeReader reader, Action`1 callback) in C:\projects\bililiverecorder\BililiveRecorder.Core\Api\Danmaku\DanmakuClient.cs:line 262
   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.ProcessDataAsync(Stream stream, Action`1 callback) in C:\projects\bililiverecorder\BililiveRecorder.Core\Api\Danmaku\DanmakuClient.cs:line 255
   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.<ConnectAsync>b__16_0() in C:\projects\bililiverecorder\BililiveRecorder.Core\Api\Danmaku\DanmakuClient.cs:line 107

[21:04:14 WRN] [**] 启动录制出错
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at BililiveRecorder.Core.Recording.RecordTask.GetStreamAsync(String fullUrl) in C:\projects\bililiverecorder\BililiveRecorder.Core\Recording\RecordTask.cs:line 315
   at BililiveRecorder.Core.Recording.RecordTask.StartAsync() in C:\projects\bililiverecorder\BililiveRecorder.Core\Recording\RecordTask.cs:line 129
   at BililiveRecorder.Core.Room.<CreateAndStartNewRecordTask>b__87_0() in C:\projects\bililiverecorder\BililiveRecorder.Core\Room.cs:line 232

[21:05:27 VRB] [**] Networking stats: {"StartTime": "2021-03-16T13:05:25.2758775+00:00", "EndTime": "2021-03-16T13:05:27.2745806+00:00", "Duration": "00:00:01.9987031", "BytesDownloaded": 0, "Mbps": 0, "$type": "NetworkingStatsEventArgs"}

[21:23:03 WRN] [] Error running ProcessDataAsync
System.IO.IOException: Unable to read data from the transport connection: Connection timed out.
 ---> System.Net.Sockets.SocketException (110): Connection timed out
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.IO.Pipelines.StreamPipeReader.ReadAsync(CancellationToken cancellationToken)
   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.ReadPipeAsync(PipeReader reader, Action`1 callback) in C:\projects\bililiverecorder\BililiveRecorder.Core\Api\Danmaku\DanmakuClient.cs:line 262
   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.ProcessDataAsync(Stream stream, Action`1 callback) in C:\projects\bililiverecorder\BililiveRecorder.Core\Api\Danmaku\DanmakuClient.cs:line 255
   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.<ConnectAsync>b__16_0() in C:\projects\bililiverecorder\BililiveRecorder.Core\Api\Danmaku\DanmakuClient.cs:line 107
```

想知道原因是出在哪方面，录播姬/网络/B站。

**Comment by Genteure** [comment]
看起来像是你的网络问题
