### ISSUE TITLE
使用 GraphiQL API 发送 removeRoom 指令出现错误

### ISSUE THREAD

**Issue by hegugu-ng** [Bililive/BililiveRecorder#227]
# 概述
您好，我在使用 `GraphiQL API`  发送 `removeRoom` 指令出现下面的错误，不知道是何原因，特开此issue。

>  System.IO.IOException: Unable to read data from the transport connection: 由于线程退出或应用程序请求，已中止 I/O 操作。

**版本与系统信息：**
* 1.4.0-web-api.1+14.Branch.feature-web-api.Sha.bc0619da087630a6a7c4c52f6031a47393c6ae27
* Win10 64bit 21H1
* Microsoft .NET Framework 4.8 (528372)

我发送的  GraphiQL 语句格式：
```GraphiQL
mutation MyMutation {
  __typename
  removeRoom(objectId: "<一个存在的id>", roomId: <一个存在的房间>) {
    name
    title
    shortId
    roomConfig {
      roomId
    }
  }
}
```
同时API 正常返回json数据，如下：
```json
{
    "code": 0,
    "data": {
        "name": "七海Nana7mi",
        "title": "头晕晕了",
        "shortId": 0,
        "roomConfig": {
            "roomId": 21452505
        }
    }
}
```
> **这里的数据经过我的处理** 

但是，API 可以返回我需要的数据，并且也可以完成删除的功能。

# 疑问描述

我对于**使用`removeRoom` 指令后** 录播姬是否会触发 `FileClosed` 事件和`SessionEnded` 存在疑问，但是我查看日志发现日志中有一下几行：
> [22:01:33 DBG] [21452505] 录制被取消

> [22:01:33 INF] [21452505] 录制结束

我个人认为是触发了的，**但是录播姬似乎没有通过`webhook`发送这个事件到我的服务器**。同时我发现日志中存在一个错误。

# 错误

上面讲到存在错误，这里将会对错误进行描述。
**完整日志如下：**
```log
[22:01:33 INF] [] Request starting HTTP/1.1 GET http://127.0.0.1:8200/graphql?query=mutation%20MyMutation%20%7B%0A%20%20__typename%0A%20%20removeRoom(objectId:%20%2249c7627d-d786-4632-88d8-6b6a0c76a4be%22,%20roomId:%2021452505)%20%7B%0A%20%20%20%20name%0A%20%20%20%20title%0A%20%20%20%20shortId%0A%20%20%20%20roomConfig%20%7B%0A%20%20%20%20%20%20roomId%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&variables=%7B%7D&operationName=MyMutation - - 
[22:01:33 DBG] [] Request is not a valid websocket request
[22:01:33 DBG] [21452505] RemoveRoom 21452505
[22:01:33 DBG] [21452505] 录制被取消
- System.OperationCanceledException: The operation was canceled.
- at System.Threading.CancellationToken.ThrowOperationCanceledException()
- at System.IO.Pipelines.Pipe.GetReadAsyncResult()
- at BililiveRecorder.Flv.Parser.FlvTagPipeReader.ReadNextTagAsync(CancellationToken cancellationToken) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Parser/FlvTagPipeReader.cs:line 64
- at BililiveRecorder.Flv.Parser.FlvTagPipeReader.ReadTagAsync(CancellationToken token) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Parser/FlvTagPipeReader.cs:line 349
- at BililiveRecorder.Flv.Grouping.TagGroupReader.ReadGroupAsync(CancellationToken token) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Grouping/TagGroupReader.cs:line 91
- at BililiveRecorder.Core.Recording.StandardRecordTask.RecordingLoopAsync() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/StandardRecordTask.cs:line 158
[22:01:33 DBG] [] Error running ProcessDataAsync
 - System.IO.IOException: Unable to read data from the transport connection: 由于线程退出或应用程序请求，已中止 I/O 操作。.
- ---> System.Net.Sockets.SocketException (995): 由于线程退出或应用程序请求，已中止 I/O 操作。
- --- End of inner exception stack trace ---
- at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
- at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
- at System.IO.Pipelines.StreamPipeReader.ReadAsync(CancellationToken cancellationToken)
- at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.ProcessDataAsync(Stream stream, Action`1 callback) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuClient.cs:line 260
- at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.<ConnectAsync>b__16_0() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuClient.cs:line 109
[22:01:33 INF] [21452505] 录制结束
[22:01:33 DBG] [] Connection id "0HMALNNLNS3BI" completed keep alive response.
[22:01:33 INF] [] Request finished HTTP/1.1 GET http://127.0.0.1:8200/graphql?query=mutation%20MyMutation%20%7B%0A%20%20__typename%0A%20%20removeRoom(objectId:%20%2249c7627d-d786-4632-88d8-6b6a0c76a4be%22,%20roomId:%2021452505)%20%7B%0A%20%20%20%20name%0A%20%20%20%20title%0A%20%20%20%20shortId%0A%20%20%20%20roomConfig%20%7B%0A%20%20%20%20%20%20roomId%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&variables=%7B%7D&operationName=MyMutation - - - 200 - application/json 4.1225ms
```
# 其他
当然这个问题经过我反复复现确定其存在，当然不排除有可能是我使用存在一些问题。
最后，万分感谢您

**Comment by Genteure** [comment]
确实是bug，最近几天修一下

**Comment by Genteure** [comment]
已 push 到 `feature/web_api` branch

Edit: GitHub Actions 上编译有问题，明天再看吧
Edit2: 已解决
