### ISSUE TITLE
磁盘空间不足的时候会无限重试调用webhook

### ISSUE THREAD

**Issue by sola97** [Bililive/BililiveRecorder#236]
![image](https://user-images.githubusercontent.com/17388849/131054389-766983c7-6438-410d-8a57-289d170d2b8f.png)
```
[08:14:48 WRN] [22874144] 录制时发生IO错误
System.IO.IOException: No space left on device
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at BililiveRecorder.Core.Danmaku.BasicDanmakuWriter.EnableWithPath(String path, IRoom room) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Danmaku/BasicDanmakuWriter.cs:line 71
   at BililiveRecorder.Core.Room.RecordTask_RecordFileOpening(Object sender, RecordFileOpeningEventArgs e) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Room.cs:line 377
   at BililiveRecorder.Core.Recording.StandardRecordTask.<.ctor>b__11_0(ValueTuple`2 paths) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/StandardRecordTask.cs:line 77
   at BililiveRecorder.Core.Recording.StandardRecordTask.WriterTargetProvider.CreateOutputStream() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/StandardRecordTask.cs:line 280
   at BililiveRecorder.Flv.Writer.FlvTagFileWriter.CreateNewFile() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Writer/FlvTagFileWriter.cs:line 64
   at BililiveRecorder.Flv.Writer.FlvProcessingContextWriter.OpenNewFileThenWriteHeadersImpl() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Writer/FlvProcessingContextWriter.cs:line 212
   at BililiveRecorder.Flv.Writer.FlvProcessingContextWriter.WriteDataTags(PipelineDataAction dataAction) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Writer/FlvProcessingContextWriter.cs:line 219
   at BililiveRecorder.Flv.Writer.FlvProcessingContextWriter.WriteAsync(FlvProcessingContext context) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Writer/FlvProcessingContextWriter.cs:line 59
   at BililiveRecorder.Core.Recording.StandardRecordTask.RecordingLoopAsync() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/StandardRecordTask.cs:line 170
[08:14:48 INF] [22874144] 录制结束
```
基本一秒两三次的频率调用webhook通知SESSION_STARTED，过于频繁

**Comment by Genteure** [comment]
个人认为最根本的解决方法还是不要让硬盘满了。
之后会用 #184 实现空间不足不启动录制的功能。
