### ISSUE TITLE
直播间标题包含特殊字符可能导致录播失败

### ISSUE THREAD

**Issue by mihirukiss** [Bililive/BililiveRecorder#239]
环境信息:
Docker
v1.3.8镜像

今天发现有个直播间一直录制失败, 不断重复生成弹幕文件, 查看生成的弹幕文件内容断在记录直播间标题的地方
```xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="#s"?>
<i>
  <!--
B站录播姬 1.3.8
本文件的弹幕信息兼容B站主站视频弹幕XML格式
本XML自带样式可以在浏览器里打开（推荐使用Chrome）

sc 为SuperChat
gift为礼物
guard为上船

attribute "raw" 为原始数据
-->
  <chatserver>chat.bilibili.com</chatserver>
  <chatid>0</chatid>
  <mission>0</mission>
  <maxlimit>1000</maxlimit>
  <state>0</state>
  <real_name>0</real_name>
  <source>0</source>
  <BililiveRecorder version="1.3.8" />
  <BililiveRecorderRecordInfo roomid="21470454" shortid="0" name="VirtuaReal" title="
```

拉了下Docker日志顺便看了下阿B直播间信息接口返回的信息, 应该是直播间标题里包含的特殊字符\u0010导致写入xml失败了
```
[22:16:01 INF] [21470454] 连接直播服务器 d1--cn-gotcha04.bilivideo.com

[22:16:01 INF] [21470454] 开始接收直播流

[22:16:01 WRN] [21470454] 启动录制出错

System.ArgumentException: '', hexadecimal value 0x10, is an invalid character.

   at System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(Int32 ch, Byte* pDst, Boolean entitize)

   at System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)

   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)

   at System.Xml.XmlWellFormedWriter.WriteString(String text)

   at System.Xml.XmlWriter.WriteAttributeString(String localName, String value)

   at BililiveRecorder.Core.Danmaku.BasicDanmakuWriter.WriteStartDocument(XmlWriter writer, IRoom room) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Danmaku/BasicDanmakuWriter.cs:line 206

   at BililiveRecorder.Core.Danmaku.BasicDanmakuWriter.EnableWithPath(String path, IRoom room) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Danmaku/BasicDanmakuWriter.cs:line 71

   at BililiveRecorder.Core.Room.RecordTask_RecordFileOpening(Object sender, RecordFileOpeningEventArgs e) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Room.cs:line 377

   at BililiveRecorder.Core.Recording.RawDataRecordTask.StartRecordingLoop(Stream stream) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/RawDataRecordTask.cs:line 48

   at BililiveRecorder.Core.Recording.RecordTaskBase.StartAsync() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/RecordTaskBase.cs:line 104

   at BililiveRecorder.Core.Room.<CreateAndStartNewRecordTask>b__86_0() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Room.cs:line 254

[22:16:01 WRN] [] 写入弹幕时发生错误

System.InvalidOperationException: The Writer is closed or in error state.

   at System.Xml.XmlWellFormedWriter.AdvanceStateAsync(Token token)

   at System.Xml.XmlWellFormedWriter.WriteStartElementAsync(String prefix, String localName, String ns)

   at System.Xml.XmlAsyncCheckWriter.WriteStartElementAsync(String prefix, String localName, String ns)

   at BililiveRecorder.Core.Danmaku.BasicDanmakuWriter.WriteAsync(DanmakuModel danmakuModel) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Danmaku/BasicDanmakuWriter.cs:line 202
```

```json
{
    "code":0,
    "msg":"ok",
    "message":"ok",
    "data":{
        "uid":413748120,
        "room_id":21470454,
        "short_id":0,
        "attention":174426,
        "online":5924161,
        "is_portrait":false,
        "description":"<p>无论你是一人成军的相声高手还是起手键来的游戏达人，亦或者是小圈子中的歌乐之王，我们都欢迎你的到来~加入我们，成为VirtuaReal的虚拟艺人吧！</p>",
        "live_status":2,
        "area_id":371,
        "parent_area_id":9,
        "parent_area_name":"虚拟主播",
        "old_area_id":6,
        "background":"",
        "title":"夏日合唱Pro Max\u0010",
        "user_cover":"https://i0.hdslb.com/bfs/live/new_room_cover/5d4a6540e4f749dcac4fb53ffa87d8d68a6e737b.jpg",
        "keyframe":"https://i0.hdslb.com/bfs/live-key-frame/keyframe08282217000021470454138fju.jpg",
        "is_strict_room":false,
        "live_time":"0000-00-00 00:00:00",
        "tags":"Vup,VTuber,虚拟主播,VirtuaReal",
        "is_anchor":0,
        "room_silent_type":"",
        "room_silent_level":0,
        "room_silent_second":0,
        "area_name":"虚拟主播",
        "pendants":"",
        "area_pendants":"",
        "hot_words":[
            "2333333",
            "喂，妖妖零吗",
            "红红火火恍恍惚惚",
            "FFFFFFFFFF",
            "Yooooooo",
            "啪啪啪啪啪",
            "666666666",
            "老司机带带我",
            "你为什么这么熟练啊",
            "gg",
            "prprpr",
            "向大佬低头",
            "请大家注意弹幕礼仪哦！",
            "还有这种操作！",
            "囍",
            "打call",
            "你气不气？",
            "队友呢？"
        ],
        "hot_words_status":0,
        "verify":"",
        "new_pendants":{
            "frame":{
                "name":"",
                "value":"",
                "position":0,
                "desc":"",
                "area":0,
                "area_old":0,
                "bg_color":"",
                "bg_pic":"",
                "use_old_area":false
            },
            "badge":{
                "name":"v_person",
                "position":3,
                "value":"",
                "desc":"虚拟主播团体VirtuaReal"
            },
            "mobile_frame":{
                "name":"",
                "value":"",
                "position":0,
                "desc":"",
                "area":0,
                "area_old":0,
                "bg_color":"",
                "bg_pic":"",
                "use_old_area":false
            },
            "mobile_badge":null
        },
        "up_session":"",
        "pk_status":0,
        "pk_id":0,
        "battle_id":0,
        "allow_change_area_time":0,
        "allow_upload_cover_time":0,
        "studio_info":{
            "status":0,
            "master_list":[

            ]
        }
    }
}
```
可能需要在写入前剔掉或者转换下一些特殊字符, 另外弹幕内容和用户名上可能也需要看下是否有类似的问题

**Comment by Genteure** [comment]
昨天晚上 https://github.com/Bililive/BililiveRecorder/commit/9337bbe9317d65b106267024aee671dbeb21838f 修过了
如果有需要可以从 GitHub Actions 里下载编译好的文件使用
