### ISSUE TITLE
Linux命令行版在录制obs推流的情况下会出现"启动录制出错"的问题

### ISSUE THREAD

**Issue by suica-me** [Bililive/BililiveRecorder#241]
A主播使用b站的直播姬，在直播开始时没有报错。
B主播使用obs推流，直播开始和结束时会出现以下错误信息，不过据观察会自动尝试然后能成功录制，但是结束时会生成一个小的录播文件。
直播服务器为海外服务器 d1--ov-gotcha05.bilivideo.com
```
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at BililiveRecorder.Core.Recording.RecordTaskBase.GetStreamAsync(String fullUrl, Int32 timeout) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/RecordTaskBase.cs:line 309
   at BililiveRecorder.Core.Recording.RecordTaskBase.StartAsync() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/RecordTaskBase.cs:line 104
   at BililiveRecorder.Core.Room.<CreateAndStartNewRecordTask>b__86_0() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Room.cs:line 254
```

**Comment by Genteure** [comment]
TLDR: 正常情况

-----

主播点了网页上的开播按钮切换直播间状态为“直播中”后，录播姬就会开始尝试录制。
直播姬的直播间状态切换和推流基本是同时开始的，所以录播姬开始录的时候已经有直播流了。
使用 OBS 直播的主播要手动点击网页上的开播按钮，再切到 OBS 点击推流，两个动作之间有一定延迟，所以录播姬开始录的时候还没有直播流。

直播结束的时候直播流先断开，可能直播间状态更新有一定延迟（直播姬）或主播还没有点网页上的关闭直播按钮（OBS），所以录播姬重试开始录制，没有直播流。

不同的直播服务器对没有直播流的表现不一样，据观察：
`d1--cn-gotcha04` 是返回 HTTP 404
`d1--ov-gotcha05` 是不返回数据，等待直播流开始

又因为录播姬默认设置了一个请求超时的时间防止网络请求卡死，所以这里出现了报错 "Operation canceled"

-----

关于结束时会生成的小录播文件

直播服务器有时在主播推流断开的时候会重复发送最后一段数据，检查一下这个小文件和上一个文件的最末尾是否是一样的内容，然后删除即可。

**Comment by suica-me** [comment]
懂了，那就和我的猜测是一样的，我这边大概几十个文件都是末尾是一样的，那就是没问题了，非常感谢
