### ISSUE TITLE
Linux命令行版出现不录制的情况

### ISSUE THREAD

**Issue by suica-me** [Bililive/BililiveRecorder#242]
今天上午录制的主播开播的时候没有开始录制，查看log发现
`{"@t":"2021-09-09T01:45:39.3654998Z","@mt":"连接直播服务器 {Host}","Host":"d1--ov-gotcha05.bilivideo.com","RoomId":~~~~,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":12617,"ThreadId":85}
`
已经连接上直播服务器但是未录制，log文件里之后就没有其他log了，Ctrl C强制终止后写入以下log
```
{"@t":"2021-09-09T03:15:30.2244909Z","@mt":"直播流地址 {Url}","@l":"Debug","Url":"~~~~","RoomId":~~~~,"SourceContext":"Bilil
iveRecorder.Core.Recording.StandardRecordTask","ProcessId":12617,"ThreadId":85}
{"@t":"2021-09-09T03:15:30.2559514Z","@mt":"Dispose called","@l":"Debug","SourceContext":"BililiveRecorder.Core.Recorder","ProcessId":12617,"ThreadId":76}
{"@t":"2021-09-09T03:15:30.2770126Z","@mt":"Error running ProcessDataAsync","@l":"Debug","@x":"System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125):
 Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.IO.Pipelines.StreamPipeReader.ReadAsync(CancellationToken cancellationToken)
   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.ProcessDataAsync(Stream stream, Action`1 callback) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuClient.cs:line 260
   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.<ConnectAsync>b__16_0() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuClient.cs:line 109","SourceContext":"BililiveRecorder.Core.Api.Danmaku.DanmakuClient","ProcessId":12617,"ThreadId":123,"ExceptionDetail":{"Type":"System.IO.IOException","HResult":-2146232800,"Message":"Unable to read data from the transport connection: Operation canceled.","Source":"System.Net.Sockets","InnerException":{"Type":"System.Net.Sockets.SocketException","HResult":-2147467259,"Message":"Operation canceled","Source":null,"SocketErrorCode":"OperationAborted","SocketErrorCodeMessage":"The overlapped operation was aborted due to the closure of the Socket."}}}
{"@t":"2021-09-09T03:15:30.2761370Z","@mt":"Error running ProcessDataAsync","@l":"Debug","@x":"System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.IO.Pipelines.StreamPipeReader.ReadAsync(CancellationToken cancellationToken)
   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.ProcessDataAsync(Stream stream, Action`1 callback) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuClient.cs:line 260
   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.<ConnectAsync>b__16_0() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuClient.cs:line 109","SourceContext":"BililiveRecorder.Core.Api.Danmaku.DanmakuClient","ProcessId":12617,"ThreadId":83,"ExceptionDetail":{"Type":"System.IO.IOException","HResult":-2146232800,"Message":"Unable to read data from the transport connection: Operation canceled.","Source":"System.Net.Sockets","InnerException":{"Type":"System.Net.Sockets.SocketException","HResult":-2147467259,"Message":"Operation canceled","Source":null,"SocketErrorCode":"OperationAborted","SocketErrorCodeMessage":"The overlapped operation was aborted due to the closure of the Socket."}}}
{"@t":"2021-09-09T03:15:30.3391155Z","@mt":"跳转到 {Url}","@l":"Debug","Url":"~~~~","RoomId":~~~~,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":12617,"ThreadId":85}
{"@t":"2021-09-09T03:15:30.6452158Z","@mt":"启动录制出错","@l":"Warning","@x":"System.Exception: 尝试下载直播流时服务器返回了 (Forbidden)Forbidden
   at BililiveRecorder.Core.Recording.RecordTaskBase.GetStreamAsync(String fullUrl, Int32 timeout) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/RecordTaskBase.cs:line 331
   at BililiveRecorder.Core.Recording.RecordTaskBase.StartAsync() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/RecordTaskBase.cs:line 104
   at BililiveRecorder.Core.Room.<CreateAndStartNewRecordTask>b__86_0() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Room.cs:line 254","RoomId":~~~~,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":12617,"ThreadId":85,"ExceptionDetail":{"Type":"System.Exception","HResult":-2146233088,"Message":"尝试下载直播流时服务器返回了 (Forbidden)Forbidden","Source":"BililiveRecorder.Core"}}
```
以上情况是无法解决的玄学网络问题还是其他的问题呢

**Comment by Genteure** [comment]
看起来像是进程被挂起了？
想不出来是什么原因，感觉不像是网络问题。

**Comment by suica-me** [comment]
是的....非常奇怪为什么会卡在那里，我现在录播姬是用screen保持后台的，昨天晚上到今天早上开播这段时间我也没去管他，如果我Ctrl z暂停了的话应该不会有 '连接直播服务器' 的提示，我这边会保持继续观察，如果有其他的情况我再报告，顺便现在的log就是debug了么，还是说还有debug mode。

**Comment by Genteure** [comment]
`连接直播服务器` 和 `直播流地址` 是紧挨着的两个日志，间隔了 1.5 小时那肯定是中间没有在运行

https://github.com/Bililive/BililiveRecorder/blob/81a36dea331dc13d9b6d6dcc22c5b798bd55596b/BililiveRecorder.Core/Recording/RecordTaskBase.cs#L81-L85

目前日志默认是输出 info 以及以上到 stdout，写入 debug 以及以上到日志文件。
可以用 `--log` 和 `--flog` 设置日志级别，具体见 `--help` 的输出。

**Comment by suica-me** [comment]
这样的话，确实就很难确认了，我贴的信息也是从日志文件里找到的，我再看看是否还会出现同样的情况吧，然后我再试试看把录播进程设置成service，非常感谢。

**Comment by suica-me** [comment]
update：
目前在 21694730 直播间发现了这个问题，在这次直播前使用的是b站的直播姬，现在使用的是OBS。
错误如下：
已经开始录播的服务器：不断的尝试录播，不断的停止录播，输出以下log：
```
System.InvalidOperationException: No script tag availible
   at BililiveRecorder.Flv.Writer.FlvProcessingContextWriter.OpenNewFileThenWriteHeadersImpl() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Writer/FlvProcessingContextWriter.cs:line 212
   at BililiveRecorder.Flv.Writer.FlvProcessingContextWriter.WriteDataTags(PipelineDataAction dataAction) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Writer/FlvProcessingContextWriter.cs:line 219
   at BililiveRecorder.Flv.Writer.FlvProcessingContextWriter.WriteAsync(FlvProcessingContext context) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Writer/FlvProcessingContextWriter.cs:line 59
   at BililiveRecorder.Core.Recording.StandardRecordTask.RecordingLoopAsync() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/StandardRecordTask.cs:line 170","RoomId":21694730,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":201167,"ThreadId":16,"ExceptionDetail":{"Type":"System.InvalidOperationException","HResult":-2146233079,"Message":"No script tag availible","Source":"BililiveRecorder.Flv
```
我在本地尝试录播发现录播不开始，输入以下log：
```
{"@t":"2021-09-13T08:12:46.3398093Z","@mt":"弹幕服务器已连接","RoomId":3749977,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":55710,"ThreadId":5}
{"@t":"2021-09-13T08:20:00.4739511Z","@mt":"Dispose called","@l":"Debug","SourceContext":"BililiveRecorder.Core.Recorder","ProcessId":55710,"ThreadId":17}
{"@t":"2021-09-13T08:20:00.4829283Z","@mt":"Error running ProcessDataAsync","@l":"Debug","@x":"System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.IO.Pipelines.StreamPipeReader.ReadAsync(CancellationToken cancellationToken)
   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.ProcessDataAsync(Stream stream, Action`1 callback) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuClient.cs:line 260
   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.<ConnectAsync>b__16_0() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuClient.cs:line 109","SourceContext":"BililiveRecorder.Core.Api.Danmaku.DanmakuClient","ProcessId":55710,"ThreadId":14,"ExceptionDetail":{"Type":"System.IO.IOException","HResult":-2146232800,"Message":"Unable to read data from the transport connection: Operation canceled.","Source":"System.Net.Sockets","InnerException":{"Type":"System.Net.Sockets.SocketException","HResult":-2147467259,"Message":"Operation canceled","Source":null,"SocketErrorCode":"OperationAborted","SocketErrorCodeMessage":"The overlapped operation was aborted due to the closure of the Socket."}}}
```
edit：
Raw的录像是正常录制的，但是因为还没有结束所以没有检查服务器的录制文件有没有问题，本地开始Raw录制的话一切正常

**Comment by Genteure** [comment]
提示 `No script tag availible` 的是哪个服务器？
我这里 `d1--cn-gotcha04` 测试正常。
如果认识主播的话可以去问一下推流是用的 RTMP 还是 SRT

---

```Dispose called ... "SourceContext":"BililiveRecorder.Core.Recorder"```
你按到 Ctrl + C 把软件退了

**Comment by suica-me** [comment]
> 提示 No script tag availible 的是哪个服务器？

提示 `No script tag availible` 的是 `d1--ov-gotcha05.bilivideo.com`，因为我本人也不在国内。

> 如果认识主播的话可以去问一下推流是用的 RTMP 还是 SRT

关于推流的方法我等他下播去问一下。

> 你按到 Ctrl + C 把软件退了

确实...因为我重启了几次，为了看看是不是撞了api限制之类的。

感谢回复

**Comment by suica-me** [comment]
update：
我去和主播确认了一下，确实是obs推的SRT流，大概问题是在这里？

**Comment by Genteure** [comment]
了解了，SRT 推上去的流在有的细节上不太一样，今天晚点我改一下处理逻辑。

这个 issue 就先关了，如果再出现最开始说的问题再 reopen。
如果有其他问题可以开新 issue

**Comment by suica-me** [comment]
了解了，感谢回复，最开始说的问题因为只有Cli，我怀疑和这个是同一个问题，非常感谢您的工作！

**Comment by Genteure** [comment]
已 push
可以等 Actions build 完后 docker pull 一下 `略:dev-1.3` 或从 Artifacts 里下载 zip

**Comment by suica-me** [comment]
了解，辛苦了！
