### ISSUE TITLE
configure命令相关,在termux上安装的完整debian上无法正常录制

### ISSUE THREAD

**Issue by dangjinghao** [Bililive/BililiveRecorder#254]
- configure相关 aliyun轻量应用amd64
在使用`./BililiveRecorder.Cli configure`命令时，如果路径包含子文件夹，例`./BililiveRecorder.Cli configure './mmm/aaa.json'`或者./BililiveRecorder.Cli configure './mmm/‘`均会报以下错误，我的用户为root账户。

Write config failed
System.UnauthorizedAccessException: Access to the path '/root/bilirec/mmm/' is denied.
     System.IO.IOException: Permission denied                                                                                                                                        
     …                                                                                                                                                                               
  at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)                                                                   
  at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)                                                                                       
  at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)                                                                                            
  at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)                                               
  at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)                                                                                      
  at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)                                                                                             
  at BililiveRecorder.Cli.Configure.ConfigureCommand.SaveConfig(ConfigV2 config, String fullPath) in ConfigureCommand.cs:218    

只有当仅填写为单个文件时比如'bbb'才能正常创建写入文件。但是在直接run该文件只会导致报错`ERR Initialize Error`。我建议自动检测工作文件夹并创建config.json文件。我通过直接导入config.json文件到某一文件夹解决。

- 在通过anlinux安装在termux中的debian系统中当录制开始时，会报以下错误。 arm64（红米k30-4g）

[13:14:14 INF] [706691] 连接直播服务器 d1--cn-gotcha03.bilivideo.com
[13:14:19 WRN] [706691] 启动录制出错
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at BililiveRecorder.Core.Recording.RecordTaskBase.GetStreamAsync(String fullUrl, Int32 timeout) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/RecordTaskBase.cs:line 309
   at BililiveRecorder.Core.Recording.RecordTaskBase.StartAsync() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/RecordTaskBase.cs:line 86
   at BililiveRecorder.Core.Room.<CreateAndStartNewRecordTask>b__86_0() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Room.cs:line 236
[13:14:25 INF] [706691] 弹幕服务器已连接

不建议即刻修复，因为平台太怪了。
而且，如果近期没有制作命令行版的使用文档的打算，我可能会自己编辑一个简单的，以防自己忘记_(:з)∠)_

**Comment by Genteure** [comment]
configure 命令传入 `/path/` 的话读写的是 `/path/config.json`，传入 `/path/a.json` 读写的是 `/path/a.json`

run 命令传入的是“工作目录”路径如 `/path`，而不是配置文件的路径如 `/path/a.json`。
`./BililiveReorder.Cli run /path/` 运行时读取的配置文件是 `/path/config.json`。

---

如果不是网络不稳定问题的话，可能是主播开播后还没有推流。

**Comment by dangjinghao** [comment]
> configure 命令传入 `/path/` 的话读写的是 `/path/config.json`，传入 `/path/a.json` 读写的是 `/path/a.json`
> 
> run 命令传入的是“工作目录”路径如 `/path`，而不是配置文件的路径如 `/path/a.json`。 `./BililiveReorder.Cli run /path/` 运行时读取的配置文件是 `/path/config.json`。
> 
> 如果不是网络不稳定问题的话，可能是主播开播后还没有推流。

针对第二个问题，我经过测试，分别在arm64和x86架构中使用对应的软件同时运行并录制同一个主播，结果只有termux上的debian的那个会报错这个错误。

**Comment by Genteure** [comment]
根据其他用户的反馈，`d1--cn-gotcha03.bilivideo.com` 一直都有连接超时/不稳定的问题。
先 close 了，有问题的话再 reopen。
