### ISSUE TITLE
Linux CLI版本录制出错

### ISSUE THREAD

**Issue by LxnChan** [Bililive/BililiveRecorder#268]
无法在Linux上面进行录制，Linux版本为`Ubuntu 20.04.3 LTS`。
<details>
<summary>Log</summary>
<pre><code>
root@lxn-server:/# ./home/lxn/userdisk0/br/BililiveRecorder.Cli r /home/lxn/userdisk0/bilirec
[11:25:13 INF] [4033043] 连接直播服务器 d1--cn-gotcha04.bilivideo.com 录制画质 10000 (原画)
[11:25:18 INF] [4033043] 弹幕服务器已连接
[11:25:18 WRN] [4033043] 启动录制出错
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at BililiveRecorder.Core.Recording.RecordTaskBase.GetStreamAsync(String fullUrl, Int32 timeout) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/RecordTaskBase.cs:line 312
   at BililiveRecorder.Core.Recording.RecordTaskBase.StartAsync() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/RecordTaskBase.cs:line 97
   at BililiveRecorder.Core.Room.<CreateAndStartNewRecordTask>b__86_0() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Room.cs:line 236

</code></pre>
</details>

感觉像是路径问题。

**Comment by Genteure** [comment]
连接直播服务器超时了，默认是 5 秒。
如果有条件的话可以换个网络环境试一下，或者可以试试调整 `TimingStreamConnect` 设置，单位是毫秒，默认设置是 5000。

**Comment by LxnChan** [comment]
> 连接直播服务器超时了，默认是 5 秒。 如果有条件的话可以换个网络环境试一下，或者可以试试调整 `TimingStreamConnect` 设置，单位是毫秒，默认设置是 5000。

又测试了一会，发现如下规律：用obs直播，必须在网页端开播再到obs里面推流才能开始直播，但是由于延迟和开播/推流不在同一时间导致中间会有一个肯定大于默认延迟的时长，此时如果录播姬处于一直运行状态则大概率报错（如用官方直播姬就不会有这个问题，因为开播和推流中间没有延迟）。建议添加一个容错处理，检测到开播时长小于一般延迟（比如10秒左右）时不报错。
我这边是把`TimingStreamConnect`参数调整到10秒就算解决问题了，实际测试大概延迟有5.x秒钟左右。

**Comment by Genteure** [comment]
这样的话，其实不用改超时设置也是可以的，属于正常情况。
请求失败之后会自动重试的，默认是等待 6 秒之后再尝试请求一次，会及时录上的。
