### ISSUE TITLE
BililiveRecorder.Cli tool fix 输出文件名带方括号会导致出错

### ISSUE THREAD

**Issue by gin3715** [Bililive/BililiveRecorder#272]
使用版本：
```
$ BililiveRecorder.Cli --version
1.3.11+Branch.tags-v1.3.11.Sha.22766242b11912ca3a3b8b65298441d6623feb07
```

输出文件名中使用方括号会导致出错
```
$ BililiveRecorder.Cli tool fix input.flv [20220123].flv

Fix ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100%

  ____
 |  _ \    ___    _ __     ___
 | | | |  / _ \  | '_ \   / _ \
 | |_| | | (_) | | | | | |  __/
 |____/   \___/  |_| |_|  \___|

╭─Input──────────────────────────╮
│ /mnt/g/bilibili-live/input.flv │
╰────────────────────────────────╯
Unhandled exception: System.InvalidOperationException: Color number must be less than or equal to 255 (was 20220123)
   at Spectre.Console.StyleParser.Parse(String text) in /_/src/Spectre.Console/StyleParser.cs:line 13
   at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 26
   at Spectre.Console.Markup..ctor(String text, Style style) in /_/src/Spectre.Console/Widgets/Markup.cs:line 47
   at Spectre.Console.TableExtensions.<>c.<AddRow>b__6_0(String column) in /_/src/Spectre.Console/Extensions/TableExtensions.cs:line 165
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Spectre.Console.TableExtensions.AddRow(Table table, String[] columns) in /_/src/Spectre.Console/Extensions/TableExtensions.cs:line 165
   at BililiveRecorder.ToolBox.Tool.Fix.FixResponse.PrintToConsole() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.ToolBox/Tool/Fix/FixResponse.cs:line 55
   at BililiveRecorder.ToolBox.ToolCommand.RunSubCommand[THandler,TRequest,TResponse](TRequest request, Boolean json, Boolean jsonIndented) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.ToolBox/ToolCommand.cs:line 104
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

另外是否会考虑提供使用老版的cli输出/纯文本输出的选项，以便脚本调用？谢谢

**Comment by Genteure** [comment]
脚本调用可以加上 `--json` 参数
这个文本显示问题之后会修

**Comment by billzbc** [comment]
Input 文件名包含方括号也有相同问题，辛苦也做一个修复

--version
2.6.3+Branch.tags-v2.6.3.Sha.25b5a81db77ad208897b2d43b99fd226a86e8442

**Comment by Genteure** [comment]
@billzbc 没有问题啊？已经是转义了的。发一下完整的命令、文件名、和报错信息吧。最好开个新 issue，不然 issue 列表里看不到我会忘。
