### ISSUE TITLE
ubuntu 22 上运行命令行版 缺少libssl

### ISSUE THREAD

**Issue by CatOverrun** [Bililive/BililiveRecorder#318]
运行环境： Ubuntu 22.04 LTS (GNU/Linux 5.15.0-30-generic x86_64)
录播姬版本：1.3.11 命令行版
问题：ubuntu 22自带 libssl3，但命令行版无法使用，运行直接弹，No usable version of libssl was found
去添加了ubuntu 21的libssl1.1的源安装后，可以启动，但无法正确使用libssl，操作文件时显示永远是
System.UnauthorizedAccessException: Access to the path '/mnt/nas/Replay/Raw/23058/20220512-215508-23058.xml' is denied.\n ---> System.IO.IOException: Permission denied\n
没有权限写入smb挂载。
之前在ubuntu 20 LTS上没有这个问题
编辑：
docker版没问题（废话）可以使用smb挂载

编辑2：
已尝试（未解决问题）：
手动安装libssl1.0.2
手动安装libssl1.1
手动安装netstandard-targeting-pack-2.1_2.1.0-1_amd64.deb

**Comment by Genteure** [comment]
你的意思是 因为 libssl 导致文件 IO `Permission denied` 吗？

https://github.com/dotnet/core/issues/7038

录播姬 1.3.11 用的应该是 .NET 5，现在 dev branch 上是 .NET 6 不知道有没有问题，扫了一眼这个 issue 里感觉应该是所有版本都有问题。

**Comment by CatOverrun** [comment]
我看项目结构上BililiveRecorder.Core 还是用的2.0？
我又去装了ubuntu 18 LTS bionic-security的libssl1.0.2，还是不行QAQ
丢这个exception
```
···System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.TypeInitializationException: The type initializer for 'SslMethods' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Ssl' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SslInitializer' threw an exception.
 ---> Interop+Crypto+OpenSslCryptographicException: error:0E076071:configuration file routines:MODULE_RUN:unknown module name
   at Interop.SslInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Ssl..cctor()
   --- End of inner exception stack trace ---
   at Interop.Ssl.SslV2_3Method()
   at Interop.Ssl.SslMethods..cctor()
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.AllocateSslContext(SslProtocols protocols, SafeX509Handle certHandle, SafeEvpPKeyHandle certKeyHandle, EncryptionPolicy policy, SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SafeDeleteSslContext..ctor(SafeFreeSslCredentials credential, SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at BililiveRecorder.Core.Api.Http.HttpApiClient.FetchAsync[T](HttpClient client, String url) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Http/HttpApiClient.cs:line 80
   at Polly.CircuitBreaker.AsyncCircuitBreakerPolicy.<>c__DisplayClass8_0`1.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.CircuitBreaker.AsyncCircuitBreakerEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, ExceptionPredicates shouldHandleExceptionPredicates, ResultPredicates`1 shouldHandleResultPredicates, ICircuitController`1 breakerController)
   at Polly.CircuitBreaker.AsyncCircuitBreakerPolicy.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.<>c__DisplayClass3_0`1.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.CircuitBreaker.AsyncCircuitBreakerPolicy.<>c__DisplayClass8_0`1.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.CircuitBreaker.AsyncCircuitBreakerEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, ExceptionPredicates shouldHandleExceptionPredicates, ResultPredicates`1 shouldHandleResultPredicates, ICircuitController`1 breakerController)
   at Polly.CircuitBreaker.AsyncCircuitBreakerPolicy.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.ImplementationAsync[TResult](Func`3 func, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, IAsyncPolicy outerPolicy, IAsyncPolicy innerPolicy)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.<>c__DisplayClass3_0`1.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.ImplementationAsync[TResult](Func`3 func, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, IAsyncPolicy outerPolicy, IAsyncPolicy innerPolicy)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.<>c__DisplayClass3_0`1.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Bulkhead.AsyncBulkheadEngine.ImplementationAsync[TResult](Func`3 action, Context context, Func`2 onBulkheadRejectedAsync, SemaphoreSlim maxParallelizationSemaphore, SemaphoreSlim maxQueuedActionsSemaphore, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.ImplementationAsync[TResult](Func`3 func, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, IAsyncPolicy outerPolicy, IAsyncPolicy innerPolicy)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at BililiveRecorder.Core.Api.PolicyWrappedApiClient`1.GetUserInfoAsync(Int32 roomid) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/PolicyWrappedApiClient.cs:line 35
   at BililiveRecorder.Core.Room.FetchUserInfoAsync() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Room.cs:line 203
   at BililiveRecorder.Core.Room.RefreshRoomInfoAsync() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Room.cs:line 166
^C
```

> 你的意思是 因为 libssl 导致文件 IO Permission denied 吗？

我觉得是的

**Comment by CatOverrun** [comment]
以及这个是之前ubuntu 22 安装 ubuntu 21.10 impish-security上的libssl1.1的报错
```
System.UnauthorizedAccessException: Access to the path '/mnt/nas/Replay/Raw/23058/20220512-233253-23058.xml' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.Xml.XmlUtf8RawTextWriter.Flush()
   at System.Xml.XmlWellFormedWriter.Flush()
   at System.Xml.XmlAsyncCheckWriter.Flush()
   at BililiveRecorder.Core.Danmaku.BasicDanmakuWriter.WriteStartDocument(XmlWriter writer, IRoom room) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Danmaku/BasicDanmakuWriter.cs:line 238
   at BililiveRecorder.Core.Danmaku.BasicDanmakuWriter.EnableWithPath(String path, IRoom room) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Danmaku/BasicDanmakuWriter.cs:line 63
   at BililiveRecorder.Core.Room.RecordTask_RecordFileOpening(Object sender, RecordFileOpeningEventArgs e) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Room.cs:line 390
   at BililiveRecorder.Core.Recording.RecordTaskBase.OnRecordFileOpening(RecordFileOpeningEventArgs e) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/RecordTaskBase.cs:line 64
   at BililiveRecorder.Core.Recording.StandardRecordTask.<.ctor>b__11_0(ValueTuple`2 paths) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/StandardRecordTask.cs:line 76
   at BililiveRecorder.Core.Recording.StandardRecordTask.WriterTargetProvider.CreateOutputStream() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/StandardRecordTask.cs:line 277
   at BililiveRecorder.Flv.Writer.FlvTagFileWriter.CreateNewFile() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Writer/FlvTagFileWriter.cs:line 61
   at BililiveRecorder.Flv.Writer.FlvProcessingContextWriter.OpenNewFileThenWriteHeadersImpl() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Writer/FlvProcessingContextWriter.cs:line 184
   at BililiveRecorder.Flv.Writer.FlvProcessingContextWriter.WriteDataTags(PipelineDataAction dataAction) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Writer/FlvProcessingContextWriter.cs:line 225
   at BililiveRecorder.Flv.Writer.FlvProcessingContextWriter.WriteAsync(FlvProcessingContext context) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Writer/FlvProcessingContextWriter.cs:line 59
   at BililiveRecorder.Core.Recording.StandardRecordTask.RecordingLoopAsync() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/StandardRecordTask.cs:line 170

```

**Comment by Genteure** [comment]
> 我看项目结构上BililiveRecorder.Core 还是用的2.0？

那个是 .NET Standard 2.0, 和 .NET 5,6,7 不是同一个东西
参考文档: https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0

https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#supported-distributions
应该是还不支持 Ubuntu 22, 暂时用 docker 吧。

**Comment by Genteure** [comment]
可以试一下从 GitHub Actions 里下载开发版试一下，用的是 .NET 6。
录播姬 1.3.11 用的是 .NET 5。

**Comment by CatOverrun** [comment]
> 应该是还不支持 Ubuntu 22, 暂时用 docker 吧。

好的，理解理解。我再多等一段时间。毕竟docker版还能用

**Comment by Genteure** [comment]
我装了个 Ubuntu 22 测试了一下，用 .NET 6 可以运行。
录播姬 1.3.11 用的是 .NET 5 所以有问题。
可以从 GitHub 里下载 dev 分支的用。
