### ISSUE TITLE
弹幕服务器连接时出错后有一定概率不会重新连接

### ISSUE THREAD

**Issue by cenyejinxi** [Bililive/BililiveRecorder#402]
共同特点为报错json .ExceptionDetail.TargetSite属性为"Void Throw()"
报错以后不会进行任何弹幕服务器连接尝试

```json
{
  "@t": "2022-09-15T12:32:00.6582613Z",
  "@mt": "连接弹幕服务器时出错",
  "@l": "Warning",
  "@x": "System.IO.IOException: Cannot access a closed stream.\n   at System.Net.Http.HttpConnection.RawConnectionStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)\n   at System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompression, ReadOnlyMemory`1 payloadBuffer)\n   at System.Net.WebSockets.ManagedWebSocket.SendAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, WebSocketMessageFlags messageFlags, CancellationToken cancellationToken)\n   at System.Net.WebSockets.ManagedWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)\n   at BililiveRecorder.Core.Api.Danmaku.DanmakuTransportWebSocket.SendAsync(Byte[] buffer, Int32 offset, Int32 count) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuTransportWebSocket.cs:line 47\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\n   at BililiveRecorder.Core.Api.Danmaku.DanmakuTransportWebSocket.SendAsync(Byte[] buffer, Int32 offset, Int32 count)\n   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.SendMessageAsync(Int32 action, String body) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuClient.cs:line 248\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\n   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.SendMessageAsync(Int32 action, String body)\n   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.ConnectAsync(Int32 roomid, DanmakuTransportMode transportMode, CancellationToken cancellationToken) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuClient.cs:line 99\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)\n   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)\n   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)\n   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)\n   at BililiveRecorder.Core.Api.Danmaku.DanmakuTransportWebSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuTransportWebSocket.cs:line 44\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)\n   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)\n   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)\n   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)\n   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)\n   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()\n   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)\n   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)\n   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)\n   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)\n   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)\n   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)\n   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)\n   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)\n   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)\n   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)\n   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)\n   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)\n   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)\n   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)\n   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync, Boolean requiresExecutionContextFlow)\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _)\n   at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()\n   at System.Threading.ThreadPoolWorkQueue.Dispatch()\n   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()\n--- End of stack trace from previous location ---\n   at BililiveRecorder.Core.Api.Danmaku.DanmakuTransportWebSocket.SendAsync(Byte[] buffer, Int32 offset, Int32 count) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuTransportWebSocket.cs:line 47\n   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.SendMessageAsync(Int32 action, String body) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuClient.cs:line 254\n   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.ConnectAsync(Int32 roomid, DanmakuTransportMode transportMode, CancellationToken cancellationToken) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuClient.cs:line 136\n   at BililiveRecorder.Core.Room.<>c__DisplayClass93_0.<<StartDamakuConnection>b__0>d.MoveNext() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Room.cs:line 350",
  "RoomId": xxx,
  "SourceContext": "BililiveRecorder.Core.Room",
  "ProcessId": 1,
  "ThreadId": 62,
  "ThreadName": ".NET ThreadPool Worker",
  "ExceptionDetail": {
    "Type": "System.IO.IOException",
    "HResult": -2146232800,
    "Message": "Cannot access a closed stream.",
    "Source": "System.Private.CoreLib",
    "TargetSite": "Void Throw()"
  }
}
```

```
System.IO.IOException: Cannot access a closed stream.
   at System.Net.Http.HttpConnection.RawConnectionStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompression, ReadOnlyMemory`1 payloadBuffer)
   at System.Net.WebSockets.ManagedWebSocket.SendAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, WebSocketMessageFlags messageFlags, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
   at BililiveRecorder.Core.Api.Danmaku.DanmakuTransportWebSocket.SendAsync(Byte[] buffer, Int32 offset, Int32 count) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuTransportWebSocket.cs:line 47
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at BililiveRecorder.Core.Api.Danmaku.DanmakuTransportWebSocket.SendAsync(Byte[] buffer, Int32 offset, Int32 count)
   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.SendMessageAsync(Int32 action, String body) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuClient.cs:line 248
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.SendMessageAsync(Int32 action, String body)
   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.ConnectAsync(Int32 roomid, DanmakuTransportMode transportMode, CancellationToken cancellationToken) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuClient.cs:line 99
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at BililiveRecorder.Core.Api.Danmaku.DanmakuTransportWebSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuTransportWebSocket.cs:line 44
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync, Boolean requiresExecutionContextFlow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _)
   at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
--- End of stack trace from previous location ---
   at BililiveRecorder.Core.Api.Danmaku.DanmakuTransportWebSocket.SendAsync(Byte[] buffer, Int32 offset, Int32 count) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuTransportWebSocket.cs:line 47
   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.SendMessageAsync(Int32 action, String body) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuClient.cs:line 254
   at BililiveRecorder.Core.Api.Danmaku.DanmakuClient.ConnectAsync(Int32 roomid, DanmakuTransportMode transportMode, CancellationToken cancellationToken) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Danmaku/DanmakuClient.cs:line 136
   at BililiveRecorder.Core.Room.<>c__DisplayClass93_0.<<StartDamakuConnection>b__0>d.MoveNext() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Room.cs:line 350
```

**Comment by Genteure** [comment]
自从给弹幕连接加了 websocket 支持了之后就偶尔有人遇到不连弹幕服务器的问题，但是重试逻辑完全没改过，找不出来问题在哪。
考虑多加几个日志输出然后发个版本再观察观察。
