### ISSUE TITLE
2.7.0 新加的 cookie regex 附近的问题，导致录播姬反复重启

### ISSUE THREAD

**Issue by komori-flag** [Bililive/BililiveRecorder#505]
### Platforms

CLI - Linux

### Version

v2.7.0

### Description

今天把2.5.0的cli批量更新成2.7.0的时候，不知道是读不了配置文件还是配置文件出错，反复重启，删除配置文件后再启动 就解决了

### Logs

```txt
      @2023-07-13T14:40:49.665497389Z [22:40:49 INF] Web host started.
      |2023-07-13T14:40:49.725668735Z Unhandled exception: System.ArgumentNullException: Value cannot be null. (Parameter 'input')
      �2023-07-13T14:40:49.725829448Z    at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
      ^2023-07-13T14:40:49.725869116Z    at System.Text.RegularExpressions.Regex.Match(String input)
      �2023-07-13T14:40:49.725896242Z    at BililiveRecorder.Core.Api.Http.HttpApiClient.UpdateHttpClient() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Http/HttpApiClient.cs:line 76
      �2023-07-13T14:40:49.725923076Z    at BililiveRecorder.Core.Api.Http.HttpApiClient..ctor(GlobalConfig config) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Api/Http/HttpApiClient.cs:line 38
      �2023-07-13T14:40:49.725949327Z    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
      �2023-07-13T14:40:49.725975577Z    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
      �2023-07-13T14:40:49.726000953Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
      �2023-07-13T14:40:49.726026620Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
      �2023-07-13T14:40:49.726051996Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
      �2023-07-13T14:40:49.726077372Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
      �2023-07-13T14:40:49.726103331Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
      �2023-07-13T14:40:49.726129290Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
      �2023-07-13T14:40:49.726154666Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
      �2023-07-13T14:40:49.726185875Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
      �2023-07-13T14:40:49.726212417Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
      �2023-07-13T14:40:49.726237501Z    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
      �2023-07-13T14:40:49.726262877Z    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
      �2023-07-13T14:40:49.726287669Z    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
      �2023-07-13T14:40:49.726312753Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
      �2023-07-13T14:40:49.726403756Z    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
      �2023-07-13T14:40:49.726435257Z    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
     2023-07-13T14:40:49.726461508Z    at BililiveRecorder.DependencyInjection.DependencyInjectionExtensions.<>c.<AddRecorderApiClients>b__3_2(IServiceProvider sp) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/DependencyInjectionExtensions.cs:line 43
      �2023-07-13T14:40:49.726492717Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
      �2023-07-13T14:40:49.726518968Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
      �2023-07-13T14:40:49.726544927Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
      �2023-07-13T14:40:49.726570302Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
      �2023-07-13T14:40:49.726595678Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
     	2023-07-13T14:40:49.726625137Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
      �2023-07-13T14:40:49.726651971Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
      �2023-07-13T14:40:49.726677639Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
      �2023-07-13T14:40:49.726703306Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
      �2023-07-13T14:40:49.726728682Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
      �2023-07-13T14:40:49.726755516Z    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
      �2023-07-13T14:40:49.726781183Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
      �2023-07-13T14:40:49.726806559Z    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
      �2023-07-13T14:40:49.726832518Z    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
      �2023-07-13T14:40:49.726858185Z    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
      �2023-07-13T14:40:49.726941021Z    at BililiveRecorder.Core.RoomFactory.CreateRoom(RoomConfig roomConfig, Int32 initDelayFactor) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/RoomFactory.cs:line 21
      �2023-07-13T14:40:49.726971063Z    at BililiveRecorder.Core.Recorder.AddRoom(RoomConfig roomConfig, Int32 initDelayFactor) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recorder.cs:line 81
      �2023-07-13T14:40:49.726998773Z    at BililiveRecorder.Core.Recorder..ctor(IRoomFactory roomFactory, ConfigV3 config, ILogger logger) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recorder.cs:line 42
      �2023-07-13T14:40:49.727031440Z    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
      �2023-07-13T14:40:49.727057983Z    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
      �2023-07-13T14:40:49.727083358Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
      �2023-07-13T14:40:49.727109026Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
      �2023-07-13T14:40:49.727134110Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
      �2023-07-13T14:40:49.727161527Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
      �2023-07-13T14:40:49.727186903Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
      �2023-07-13T14:40:49.727211987Z    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
      �2023-07-13T14:40:49.727237071Z    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
      �2023-07-13T14:40:49.727261863Z    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
      {2023-07-13T14:40:49.727286947Z    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
      �2023-07-13T14:40:49.727312323Z    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
      �2023-07-13T14:40:49.727337115Z    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
      �2023-07-13T14:40:49.727362199Z    at BililiveRecorder.Cli.Program.RunRecorderAsync(IServiceProvider serviceProvider, SharedArguments sharedArguments) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Cli/Program.cs:line 291
      �2023-07-13T14:40:49.727393117Z    at BililiveRecorder.Cli.Program.RunConfigModeAsync(RunModeArguments args) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Cli/Program.cs:line 144
      �2023-07-13T14:40:49.727464869Z    at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
      �2023-07-13T14:40:49.727493453Z    at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
      �2023-07-13T14:40:49.727519120Z    at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.Invoke(InvocationContext context)
      �2023-07-13T14:40:49.727544204Z    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
      Q2023-07-13T14:40:49.727569580Z --- End of stack trace from previous location ---
      �2023-07-13T14:40:49.727593789Z    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
      Q2023-07-13T14:40:49.727619748Z --- End of stack trace from previous location ---
      �2023-07-13T14:40:49.727643957Z    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
      Q2023-07-13T14:40:49.727669333Z --- End of stack trace from previous location ---
      �2023-07-13T14:40:49.727693542Z    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
      Q2023-07-13T14:40:49.727718918Z --- End of stack trace from previous location ---
      �2023-07-13T14:40:49.727743127Z    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
      Q2023-07-13T14:40:49.727768794Z --- End of stack trace from previous location ---
      �2023-07-13T14:40:49.727793295Z    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
      Q2023-07-13T14:40:49.727818379Z --- End of stack trace from previous location ---
      �2023-07-13T14:40:49.727842588Z    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
      Q2023-07-13T14:40:49.727868547Z --- End of stack trace from previous location ---
      �2023-07-13T14:40:49.727893339Z    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
      Q2023-07-13T14:40:49.727918715Z --- End of stack trace from previous location ---
      �2023-07-13T14:40:49.727943507Z    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by komori-flag** [comment]
帮开的issue，来源反馈群
![QQ截图20230713233742](https://github.com/BililiveRecorder/BililiveRecorder/assets/105255344/9b417763-d50d-4427-9b6c-208244b86618)
![QQ截图20230713233750](https://github.com/BililiveRecorder/BililiveRecorder/assets/105255344/df5537ce-9095-4ce3-8d6e-f4750f29bf71)
